#
# Seeds for the Location model
#   This file just contains some sample locations. (At least one) Location
#   must exist within the system, as a User must have a Location.
#

Location.create!(name: 'Earth', description: 'Planet Earth, Solar System, Milkyway Galaxy')
Location.create!(name: 'Mars', description: 'Planet Mars, Solar System, Milkyway Galaxy')
Location.create!(name: 'Saturn', description: 'Planet Saturn, Solar System, Milkyway Galaxy')
Location.create!(name: 'Jupiter', description: 'Planet Jupiter, Solar System, Milkyway Galaxy')
Location.create!(name: 'Pluto', description: 'Dwarf Planet Pluto, Solar System, Milkyway Galaxy')
Location.create!(name: 'Venus', description: 'Planet Venus, Solar System, Milkyway Galaxy')
Location.create!(name: 'Mercury', description: 'Planet Mercury, Solar System, Milkyway Galaxy')
Location.create!(name: 'Uranus', description: 'Planet Uranus, Solar System, Milkyway Galaxy')
Location.create!(name: 'Neptune', description: 'Planet Neptune, Solar System, Milkyway Galaxy')
Location.create!(name: 'Edinburgh', description: 'City, UK, Europe')
Location.create!(name: 'Glasgow', description: 'City, UK, Europe')
Location.create!(name: 'Coatbridge', description: 'City, UK, Europe')
Location.create!(name: 'Reading', description: 'City, UK, Europe')
Location.create!(name: 'London', description: 'City, UK, Europe')
Location.create!(name: 'Liverpool', description: 'City, UK, Europe')
Location.create!(name: 'Manchester', description: 'City, UK, Europe')
Location.create!(name: 'Newcastle', description: 'City, UK, Europe')
Location.create!(name: 'Paris', description: 'City, France, Europe')
Location.create!(name: 'Rome', description: 'City, Italy, Europe')
Location.create!(name: 'Venice', description: 'City, Italy, Europe')
Location.create!(name: 'Madrid', description: 'City, Spain, Europe')
Location.create!(name: 'Barcelona', description: 'City, Spain, Europe')
Location.create!(name: 'Moscow', description: 'City, Russia, Europe')
Location.create!(name: 'Berlin', description: 'City, Germany, Europe')
Location.create!(name: 'Istanbul', description: 'City, France, Europe')
Location.create!(name: 'New York', description: 'City, USA, North America')
Location.create!(name: 'Los Angeles', description: 'City, USA, North America')
Location.create!(name: 'Dallas', description: 'City, USA, North America')
Location.create!(name: 'Chicago', description: 'City, USA, North America')
Location.create!(name: 'Detroit', description: 'City, USA, North America')
Location.create!(name: 'Philadelphia', description: 'City, USA, North America')
Location.create!(name: 'Miami', description: 'City, USA, North America')
Location.create!(name: 'New Orleans', description: 'City, USA, North America')
Location.create!(name: 'Seattle', description: 'City, USA, North America')
Location.create!(name: 'San Francisco', description: 'City, USA, North America')
Location.create!(name: 'Vancouver', description: 'City, USA, North America')
Location.create!(name: 'Montreal', description: 'City, USA, North America')
Location.create!(name: 'Ontario', description: 'City, USA, North America')
Location.create!(name: 'Nova Scotia', description: 'City, USA, North America')
Location.create!(name: 'Ottawa', description: 'City, USA, North America')
Location.create!(name: 'Anatomy Park', description: 'Theme Park, Homeless Man, North America')
Location.create!(name: 'Purge Planet', description: 'Planet, Distant Solar System, Andromeda Galaxy')
Location.create!(name: 'Jerryboree', description: 'Asteroid, Distant Solar System, Andromeda Galaxy')
Location.create!(name: 'Gazorpazorp', description: 'Planet, Distant Solar System, Andromeda Galaxy')
Location.create!(name: 'Gear World', description: 'Planet, Distant Solar System, Andromeda Galaxy')
Location.create!(name: 'Krypton', description: 'Planet, Distant Solar System, Andromeda Galaxy')
Location.create!(name: 'Shire', description: 'Village, Middle Earth, Unknown Galaxy')
