#seeds
Project.create!(name: 'Seed_Excursion', description: 'Project', code: '001', project_type: ProjectType.find_by(name: 'scientific'))
Project.create!(name: 'Interdimensional_Travel', description: 'Project', code: '002', project_type: ProjectType.find_by(name: 'scientific'))
Project.create!(name: 'Air_Traffic_Automation', description: 'Project', code: '003', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'FAA_Professional_Services', description: 'Project', code: '004', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Airport_Planning_and_Forecasting', description: 'Project', code: '005', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Airport_Operational_Systems', description: 'Project', code: '007', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Drone_Protection', description: 'Project', code: '008', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Foreign_Object_Debris_Detection', description: 'Project', code: '009', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Fuels_Management', description: 'Project', code: '010', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Baggage_and_Cargo_Scanning', description: 'Project', code: '011', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Distributed_Network_Ground_Sensing', description: 'Project', code: '012', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Electronic_Warfare', description: 'Project', code: '013', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Radiation_and_Radiography', description: 'Project', code: '014', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Common_Driver_Trainer', description: 'Project', code: '015', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Soldier_Monitoring_System', description: 'Project', code: '016', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Application_Development', description: 'Project', code: '017', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Application_Integration', description: 'Project', code: '018', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Agile_Software_Development', description: 'Project', code: '019', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Mission_IT', description: 'Project', code: '020', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Implementation_Services', description: 'Project', code: '021', project_type: ProjectType.find_by(name: 'Health'))
Project.create!(name: 'Optimization_Services', description: 'Project', code: '022', project_type: ProjectType.find_by(name: 'Health'))
Project.create!(name: 'Advisory_Services', description: 'Project', code: '023', project_type: ProjectType.find_by(name: 'Health'))
Project.create!(name: 'Health_Cyber', description: 'Project', code: '024', project_type: ProjectType.find_by(name: 'Health'))
Project.create!(name: 'Advanced_Analytics', description: 'Project', code: '025', project_type: ProjectType.find_by(name: 'Health'))
Project.create!(name: 'Integrated_Survey_System', description: 'Project', code: '026', project_type: ProjectType.find_by(name: 'Advanced Solutions'))
Project.create!(name: 'Combatant_Craft_Medium', description: 'Project', code: '027', project_type: ProjectType.find_by(name: 'Advanced Solutions'))
Project.create!(name: 'Cloud_Migration', description: 'Project', code: '028', project_type: ProjectType.find_by(name: 'Civil'))
