#seeds
Project.create!(name: 'seed_excursion', code: '001', project_type: ProjectType.find_by(name: 'scientific'))
Project.create!(name: 'interdimensional_travel', code: '002', project_type: ProjectType.find_by(name: 'scientific'))
Project.create!(name: 'Air_Traffic_Automation', code: '003', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'FAA_Professional_Services', code: '004', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Airport_Planning_and_Forecasting', code: '005', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Airport_Operational_Systems', code: '007', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Drone_Protection', code: '008', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Foreign_Object_Debris_Detection', code: '009', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Fuels_Management', code: '010', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Baggage_and_Cargo_Scanning', code: '011', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Distributed_Network_Ground_Sensing', code: '012', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Electronic_Warfare', code: '013', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Radiation_and_Radiography', code: '014', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Common_Driver_Trainer', code: '015', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Soldier_Monitoring_System', code: '016', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Application_Development', code: '017', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Application_Integration', code: '018', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Agile_Software_Development', code: '019', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Mission_IT', code: '020', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Implementation_Services', code: '021', project_type: ProjectType.find_by(name: 'Health'))
Project.create!(name: 'Optimization_Services', code: '022', project_type: ProjectType.find_by(name: 'Health'))
Project.create!(name: 'Advisory_Services', code: '023', project_type: ProjectType.find_by(name: 'Health'))
Project.create!(name: 'Health_Cyber', code: '024', project_type: ProjectType.find_by(name: 'Health'))
Project.create!(name: 'Advanced_Analytics', code: '025', project_type: ProjectType.find_by(name: 'Health'))
Project.create!(name: 'Integrated_Survey_System', code: '026', project_type: ProjectType.find_by(name: 'Advanced Solutions'))
Project.create!(name: 'Combatant_Craft_Medium', code: '027', project_type: ProjectType.find_by(name: 'Advanced Solutions'))
Project.create!(name: 'Cloud_Migration', code: '028', project_type: ProjectType.find_by(name: 'Civil'))
