#seeds
Project.create!(name: 'Seed Excursion', description: 'Project', code: '001', project_type: ProjectType.find_by(name: 'Scientific'))
Project.create!(name: 'Interdimensional Travel', description: 'Project', code: '002', project_type: ProjectType.find_by(name: 'Scientific'))
Project.create!(name: 'Air Traffic Automation', description: 'Project', code: '003', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'FAA Professional Services', description: 'Project', code: '004', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Airport Planning and Forecasting', description: 'Project', code: '005', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Airport Operational Systems', description: 'Project', code: '007', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Drone Protection', description: 'Project', code: '008', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Foreign Object Debris Detection', description: 'Project', code: '009', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Fuels Management', description: 'Project', code: '010', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Baggage and Cargo Scanning', description: 'Project', code: '011', project_type: ProjectType.find_by(name: 'Civil'))
Project.create!(name: 'Distributed Network Ground Sensing', description: 'Project', code: '012', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Electronic Warfare', description: 'Project', code: '013', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Radiation and Radiography', description: 'Project', code: '014', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Common Driver Trainer', description: 'Project', code: '015', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Soldier Monitoring System', description: 'Project', code: '016', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Application Development', description: 'Project', code: '017', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Application Integration', description: 'Project', code: '018', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Agile Software Development', description: 'Project', code: '019', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Mission IT', description: 'Project', code: '020', project_type: ProjectType.find_by(name: 'Defense & Intelligence'))
Project.create!(name: 'Implementation Services', description: 'Project', code: '021', project_type: ProjectType.find_by(name: 'Health'))
Project.create!(name: 'Optimization Services', description: 'Project', code: '022', project_type: ProjectType.find_by(name: 'Health'))
Project.create!(name: 'Advisory Services', description: 'Project', code: '023', project_type: ProjectType.find_by(name: 'Health'))
Project.create!(name: 'Health Cyber', description: 'Project', code: '024', project_type: ProjectType.find_by(name: 'Health'))
Project.create!(name: 'Advanced Analytics', description: 'Project', code: '025', project_type: ProjectType.find_by(name: 'Health'))
Project.create!(name: 'Integrated Survey System', description: 'Project', code: '026', project_type: ProjectType.find_by(name: 'Advanced Solutions'))
Project.create!(name: 'Combatant Craft Medium', description: 'Project', code: '027', project_type: ProjectType.find_by(name: 'Advanced Solutions'))
Project.create!(name: 'Cloud Migration', description: 'Project', code: '028', project_type: ProjectType.find_by(name: 'Civil'))
