language: ruby
cache: bundler
rvm:
  - 2.3.2

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  # Run rubocop
  - bundle exec rubocop
  # Run Test Suite
  - bundle exec rake
