language: ruby
cache: bundler
rvm:
  - 2.3.3

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  # Set up database
  - RAILS_ENV=test bundle exec rake db:test:prepare
  # Run tests
  - RAILS_ENV=test bundle exec rspec -f d
  # Run rubocop
  - bundle exec rubocop -f fu -D -E
